config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  get "/login/google", to: redirect("/auth/google_oauth2")
  get "login/facebook", to: redirect("/auth/facebook")
  post "/login", to: "sessions#create"
  get "/auth/:provider/callback", to: "sessions#callback"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :account_activations, only: [:edit]
  resources :products, only: [:index, :show]
  
  namespace :admin do
    get "/", to: "dashbroads#index"
    resources :categories
    resources :products
    resources :promotions
    resources :type_products
  end

  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only"><%= t "admin.dashbroad.header.navbar-toggle" %></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <%= link_to t("admin.dashbroad.title"), admin_path, class: "navbar-brand" %>
  </div>

  <ul class="nav navbar-top-links navbar-right">
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          <i class="fa fa-user fa-fw"></i> <%= current_user.name %> <i class="fa fa-caret-down"></i>
      </a>
      <ul class="dropdown-menu dropdown-user">
        <li>
          <%= link_to current_user  do %>
            <i class="fa fa-user fa-fw"></i> <%= t ".user_profile" %>
          <% end %>
        <li class="divider"></li>
          <%= link_to logout_path, method: :delete  do %>
            <i class="fa fa-sign-out fa-fw"></i> <%= t ".logout" %>
          <% end %>
        </li>
      </ul>
    </li>
  </ul>

  <div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
      <ul class="nav" id="side-menu">
          <li class="sidebar-search">
            <div class="input-group custom-search-form">
              <%= text_field_tag "search", nil, placeholder: "Search..." ,class: "form-control" %>
              <span class="input-group-btn">
              <button class="btn btn-default" type="button">
                  <i class="fa fa-search"></i>
              </button>
            </span>
            </div>
          </li>
          <li>
            <%= link_to admin_path do %>
              <i class="fa fa-dashboard fa-fw"></i> <%= t ".home" %>
            <% end %>
          </li>
          <li>
            <%= link_to admin_categories_path do %>
              <i class="fa fa-bookmark fa-fw"></i> <%= t ".category" %>
            <% end %>
          </li>
          <li>
            <%= link_to admin_products_path do %>
              <i class="fa fa-flag fa-fw"></i> <%= t ".product" %>
            <% end %>
            <ul class="nav nav-second-level">
              <li>
                <%= link_to admin_products_path do %>
                  <i class="fa fa-shopping-bag fa-fw"></i> 
                  <%= t ".product" %>
                <% end %>
              </li>
              <li>
                <%= link_to admin_type_products_path do %>
                  <i class="fa fa-map fa-fw"></i> 
                  <%= t ".type_product" %>
                <% end %>
              </li>
            </ul>
          </li>
           <li>
            <%= link_to admin_promotions_path do %>
              <i class="fa fa-tag fa-fw"></i> <%= t ".promotion" %>
            <% end %>
          </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>

    <%= stylesheet_link_tag "admin/style", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "admin/main", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id="wrapper">  
     <%= render "layouts/admin/header" %>
     <div id="page-wrapper">
        <div class="row">
          <div class="col-lg-12">
            <%= render "shared/flash_messages" %>  
            <%= yield %>
            </div>
          </div>
        </div>
    </div>
  </body>
</html>