config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  get "/login/google", to: redirect("/auth/google_oauth2")
  get "login/facebook", to: redirect("/auth/facebook")
  post "/login", to: "sessions#create"
  get "/auth/:provider/callback", to: "sessions#callback"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :account_activations, only: [:edit]
  resources :products, only: [:index, :show]
  
  namespace :admin do
    get "/", to: "dashbroads#index"
    resources :categories
    resources :products
    resources :promotions
    resources :type_products
  end

  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  has_many :product_promotions, dependent: :destroy
  has_many :products, through: :product_promotions

  validates :name, :description, :start_date, :end_date, presence: true
  validate :start_date_before_end_date

  accepts_nested_attributes_for :product_promotions, allow_destroy: true
  scope :search, (lambda do |keyword|
    keyword = keyword.to_s.strip
    where "name LIKE ?", "%#{sanitize_sql_like keyword}%" unless keyword.blank?
  end)

  private
  def start_date_before_end_date
    return unless start_date && end_date && start_date > end_date
    errors.add :start_date, I18n.t("validate.date")
  end
end

app/controllers/admin/promotions_controller.rb
class Admin::PromotionsController < Admin::BaseController
  helper_method :sort_col, :sort_dir
  before_action :load_promotion, except: [:index, :new, :create]
  def index
    @promotions = Promotion.search(params[:search])
                           .order("#{sort_col} #{sort_dir}")
                           .page(params[:page])
                           .per Settings.page.per
  end

  def show; end

  def new
    @promotion = Promotion.new
    @promotion.product_promotions.build
  end

  def create
    @promotion = Promotion.new promotion_params
    if @promotion.save
      flash[:success] = t ".success"
      redirect_to admin_promotions_url
    else
      render :new
    end
  end

  def edit; end

  def update; end

  def destroy; end

  def sort_col
    Promotion.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  private
  def promotion_params
    params.require(:promotion).permit :name, :description, :start_date,
      :end_date, product_promotions_attributes: [:product_id, :percent]
  end

  def load_promotion
    @promotion = Promotion.find_by(id: params[:id]) || not_found
  end
end

app/views/admin/promotions/_form.html.erb
<div class="col-xs-10 col-xs-offset-1 col-sm-10 col-sm-offset-1 col-md-8 col-offset-2 col-lg-8 col-lg-offset-2">
  <%= form_for [:admin, @promotion] do |f| %>
    <%= render "shared/error_messages", object: f.object %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, size: "10x10", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :start_date %>
      <%= f.date_field :start_date, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :end_date %>
      <%= f.date_field :end_date, class: "form-control" %>
    </div>

    <%= link_to_add_fields "Add a Contact", f, :product_promotions %>

    <div class="new-field">
      <%= f.fields_for :product_promotions do |builder| %>
        <%= render "product_promotion_fields", f: builder %>
      <% end %>
    </div>

    <div class="text-center">
      <%= f.submit yield(:btn_text), class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/admin/promotions/_product_promotion_fields.html.erb
<fieldset class="field">
  <a href="#" class="remove_field">remove</a>
  <div class="form-group field">
      <%= f.label :product_id %>
      <%= f.collection_select :product_id, Product.all, :id, :name, 
      {prompt: true}, {class: "form-control"} %>
    </div>
  <div class="form-group field">
    <%= f.label :percent %>
    <%= f.text_field :percent, class: "form-control" %>
  </div>
</fieldset>

app/views/admin/promotions/_promotion.html.erb
<tr>
  <td><%= promotion.id %></td>
  <td><%= promotion.description %></t>
  <td><%= promotion.name %></td>
  <td><%= promotion.start_date %></td>
  <td><%= promotion.end_date %></td>
  <td><%= link_to t("admin.show"), admin_promotion_path(promotion) %></td>
  <td><%= link_to t("admin.edit"), edit_admin_promotion_path(promotion) %></td>
  <td><%= link_to t("admin.delete"), admin_promotion_path(id: promotion.id), method: :delete, data: { confirm: t(".you_sure") } %></td>
</tr>

app/views/admin/promotions/edit.html.erb
<% provide :title, t(:home_title) %>
<% provide :btn_text, t(".submit") %>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="h2 text-center"><%= t ".title" %></div>
  </div>
  <div class="panel-body">
    <div class="margin-top-15 margin-left-15">
      <%= link_to t("admin.back"), admin_promotions_path, class:"btn btn-success" %>
    </div>
    <%= render "form", promotion: @promotion %>
  </div>  
</div>

app/views/admin/promotions/index.html.erb
<% provide :title, t(".title") %>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-primary">
        <div class="panel-heading">
          <div class="h2 text-center"><%= t ".title" %></div>
        </div>
      </div>
      <div class="panel-body">
        <!-- search box -->
        <div class="row">
          <div class="col-md-8 col-md-offset-2">
            <%= form_tag admin_products_path, method: :get do %>
              <div class="input-group">
                <%= text_field_tag "search", params[:search], placeholder: t(".placeholer"), class: "form-control"%>
                <div class="input-group-btn">
                  <%= button_tag(type: "submit", class: "btn btn-default") do %>
                    <i class="fa fa-search"></i>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <!-- close search box -->
        <!-- button new product -->
        <div class="text-right">
          <%= link_to new_admin_promotion_path, class: "btn btn-primary" do %>
           <i class="fa fa-plus fa-2x" aria-hidden="true"></i>
          <% end %>
        </div>
        <!-- close button new product -->
        <!-- table product -->
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th><%= t ".id" %></th>
              <th><%= sort_link t(".name") %></th>
              <th><%= t ".descriptions" %></th>
              <th><%= sort_link t(".start_date") %></th>
              <th><%= sort_link t(".end_date") %></th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <%= render partial: "promotion", collection: @promotions %>
          </tbody>
        </table>
        <!-- close table product -->
        <div class="text-center">
          <%= paginate @promotions, theme: "twitter-bootstrap-3" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/promotions/new.html.erb
<% provide :title, t(:home_title) %>
<% provide :btn_text, t(".submit") %>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="h2 text-center"><%= t ".title" %></div>
  </div>
  <div class="panel-body">
    <div class="margin-top-15 margin-left-15">
      <%= link_to t("admin.back"), admin_promotions_path, class:"btn btn-success" %>
    </div>
    :<%= render partial: "form" %>
  </div>  
</div>