config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  get "/login/google", to: redirect("/auth/google_oauth2")
  get "login/facebook", to: redirect("/auth/facebook")
  post "/login", to: "sessions#create"
  get "/auth/:provider/callback", to: "sessions#callback"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :account_activations, only: [:edit]
  resources :products, only: [:index, :show]
  
  namespace :admin do
    get "/", to: "dashbroads#index"
    resources :categories
    resources :products
    resources :promotions
    resources :type_products
  end

  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :product, dependent: :destroy

  validates :name, presence: true,
    length: {maximum: Settings.category.name.maximum,
             too_long: I18n.t("validate.maximum")}
  scope :search, (lambda do |keyword|
    keyword = keyword.to_s.strip
    where "name LIKE ?", "%#{sanitize_sql_like keyword}%" unless keyword.blank?
  end)
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :load_category, except: [:index, :new, :create]
  helper_method :sort_col, :sort_dir
  def index
    @categories = Category.search(params[:search])
                          .order("#{sort_col} #{sort_dir}")
                          .page(params[:page])
                          .per Settings.page.per
  end

  def new
    @category = current_user.categories.build
  end

  def create
    @category = current_user.categories.build category_params
    if @category.save
      flash[:success] = t ".success"
      redirect_to admin_categories_url
    else
      render :new
    end
  end

  def edit; end

  def update
    if @category.update_attributes category_params
      flash[:success] = t ".success"
      redirect_to admin_categories_url
    else
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t ".success"
      redirect_to admin_categories_url
    else
      flash.now[:warning] = t ".warning"
    end
  end

  def sort_col
    Category.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  private
  def load_category
    @category = Category.find_by id: params[:id] || not_found
  end

  def category_params
    params.require(:category).permit :name
  end
end

app/views/admin/categories/_category.html.erb
 <tr>
  <td><%= category.id %></td>
  <td><%= category.name %></td>
  <td><%= link_to t("admin.edit"), edit_admin_category_path(category) %></td>
  <td><%= link_to t("admin.delete"), admin_category_path(id: category.id), method: :delete, data: { confirm: t(".you_sure") } %></td>
</tr>

app/views/admin/categories/_form.html.erb
<div class="col-xs-10 col-xs-offset-1 col-sm-10 col-sm-offset-1 col-md-8 col-offset-2 col-lg-8 col-lg-offset-2">
  <%= form_for [:admin, @category]  do |f| %>
    <%= render "shared/error_messages", object: f.object %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="text-center">
      <%= f.submit yield(:btn_text), class: "btn btn-primary mt-1" %>
    </div>
    
  <% end %>
</div>

app/views/admin/categories/edit.html.erb
<% provide :title, t(:home_title) %>
<% provide :btn_text, t(".submit") %>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="h2 text-center">
      <%= t "admin.categories.edit.title" %>
    </div>
  </div>
  <div class="margin-top-15 margin-left-15">
    <%= link_to t("admin.back"), admin_categories_path, class:"btn btn-success" %>
  </div>
  <div class="panel-body">
    <%= render "form", category: @category %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<% provide :title, t(:home_title) %>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-primary">
        <div class="panel-heading">
          <div class="h2 text-center"><%= t ".title" %></div>
        </div>
      </div>
      <div class="panel-body">
        <!-- search box -->
        <div class="row">
          <div class="col-md-8 col-md-offset-2">
            <%= form_tag admin_categories_path, method: :get do %>
              <div class="input-group">
                <%= text_field_tag "search", params[:search], placeholder: t(".placeholer"), class: "form-control"%>
                <div class="input-group-btn">
                  <%= button_tag(type: "submit", class: "btn btn-default") do %>
                    <i class="fa fa-search"></i>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <!-- close search box -->
        <!-- button new category -->
        <div class="text-right">
          <%= link_to new_admin_category_path, class: "btn btn-primary" do %>
           <i class="fa fa-plus fa-2x" aria-hidden="true"></i>
          <% end %>
        </div>
        <!-- close button new category -->
        <!-- table category -->
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th><%= t ".id" %></th>
              <th><%= sort_link t(".name") %></th>
              <th colspan="2"></th>
            </tr>
          </thead>
          <tbody>
            <%= render partial: "category", collection: @categories %>
          </tbody>
        </table>
        <!-- close table category -->
        <div class="text-center">
          <%= paginate @categories, theme: "twitter-bootstrap-3" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/new.html.erb
<% provide :title, t(:home_title) %>
<% provide :btn_text, t("admin.category.new.submit") %>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="h2 text-center"><%= t "admin.category.new.title" %></div>
  </div>
  <div class="panel-body">
    <div class="margin-top-15 magin-left-15">
      <%= link_to t("admin.back"), categories_path, class:"btn btn-success" %>
    </div>
    <%= render "form", category: @category %>
  </div>
</div>