config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  get "/login/google", to: redirect("/auth/google_oauth2")
  get "login/facebook", to: redirect("/auth/facebook")
  post "/login", to: "sessions#create"
  get "/auth/:provider/callback", to: "sessions#callback"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :account_activations, only: [:edit]
  resources :products, only: [:index, :show]
  
  namespace :admin do
    get "/", to: "dashbroads#index"
    resources :categories
    resources :products
    resources :promotions
    resources :type_products
  end

  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :ratings
  has_many :comments
  has_many :type_products, dependent: :destroy
  has_many :product_promotions, dependent: :destroy
  has_many :images, dependent: :destroy
  validates :name, :price, :descriptions, presence: true
  accepts_nested_attributes_for :type_products, allow_destroy: true
  scope :new_products, (lambda do
                          where("created_at >= ?",
                            Settings.rules_new_product.days.ago)
                        .order("created_at desc")
                        end)

  scope :search, (lambda do |keyword|
    keyword = keyword.to_s.strip
    unless keyword.blank?
      joins(:category).where "categories.name LIKE ? or products.name LIKE ?
      or price LIKE ? ", "%#{sanitize_sql_like keyword}%",
        "%#{sanitize_sql_like keyword}%", "%#{sanitize_sql_like keyword}%"
    end
  end)

  scope :filter_by_price, (lambda do |min_price, max_price|
    unless min_price.blank? && max_price.blank?
      sql_statement = "price >= ? AND price <= ?"
      where(sql_statement, min_price, max_price).order(price: :asc)
    end
  end)

  scope :filter_by_color, (lambda do |color|
    color = color.to_s.strip
    unless color.blank?
      sql_statement = "type_products.color LIKE ? "
      joins(:type_products).where(sql_statement, color)
    end
  end)

  scope :filter_by_size, (lambda do |size|
    unless size.blank?
      sql_statement = "type_products.size LIKE ? "
      joins(:type_products).where(sql_statement, size)
    end
  end)

  scope :order_by_time,
    ->{order(:name, :price, :descriptions, created_at: :asc)}

  def new_product?
    created_at >= Settings.rules_new_product.days.ago
  end

  def show_img
    path = ActionController::Base.helpers.image_path(Settings.picture.default)
    images.first ? images.first.image_url : path
  end

  def show_all_img
    images.to_a.map(&:image_url)
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :load_product, except: [:index, :new, :create]
  helper_method :sort_col, :sort_dir

  def index
    @products = Product.search(params[:search])
                       .order("#{sort_col} #{sort_dir}")
                       .page(params[:page])
                       .per Settings.page.per
  end

  def show; end

  def new
    @product = current_user.products.build
    @product.type_products.build
  end

  def create
    @product = current_user.products.new product_params
    if @product.save
      flash[:success] = t ".success"
      redirect_to admin_products_url
    else
      render :new
    end
  end

  def update
    if @product.update_attributes product_params
      flash[:success] = t ".success"
      redirect_to admin_products_url
    else
      render :edit
    end
  end

  def destroy
    if @product.destroy
      flash[:success] = t ".success"
      redirect_to admin_products_url
    else
      flash.now[:warning] = t ".warning"
    end
  end

  def sort_col
    Product.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end

  private

  def load_product
    @product = Product.find_by id: params[:id] || not_found
  end

  def product_params
    params.require(:product).permit :name, :price, :category_id, :descriptions,
      type_products_attributes: [:quantity, :size, :color, :_destroy]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :logged_in_user

  def index
    min_price = params[:min_price].to_i
    max_price = params[:max_price].to_i
    if min_price > max_price
      flash[:danger] = t ".eror"
      redirect_to products_path
    end
    @products = Product.search(params[:find])
      .filter_by_price(params[:min_price], params[:max_price])
      .filter_by_color(params[:color])
      .filter_by_size(params[:size])
      .page(params[:page])
      .per Settings.page.product
  end

  def show
    @product = Product.find_by id: params[:id] || not_found
  end

  private

  def logged_in_user
    return if logged_in?
    flash[:danger] = t ".please_login"
    redirect_to login_path
  end
end

app/views/admin/products/_form.html.erb
<div class="col-xs-10 col-xs-offset-1 col-sm-10 col-sm-offset-1 col-md-8 col-offset-2 col-lg-8 col-lg-offset-2">
  <%= form_for [:admin, @product] do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <h4><%= t "product" %></h4>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :price %>
      <%= f.number_field :price, step: 0.01, min: 0, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :descriptions %>
      <%= f.text_area :descriptions, size: "10x10", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :category_id %>
      <%= f.collection_select :category_id, Category.all, :id, :name, prompt: true, class: "form-control" %>
    </div>
    <%= link_to_add_fields t("add_type_product"), f ,:type_products %> 
    <div class="new-fields">
      <%= f.fields_for :type_products do |builder| %>
        <%= render "type_product_fields", f: builder %>
      <% end %>
    </div>
     <%= f.submit yield(:btn_text), class: "btn btn-primary" %>     
  <% end %>
</div>

app/views/admin/products/_form_edit.html.erb
<div class="col-xs-10 col-xs-offset-1 col-sm-10 col-sm-offset-1 col-md-8 col-offset-2 col-lg-8 col-lg-offset-2">
  <%= form_for [:admin, @product] do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <h4><%= t "product" %></h4>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :price %>
      <%= f.number_field :price, step: 0.01, min: 0, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :descriptions %>
      <%= f.text_area :descriptions, size: "10x10", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :category_id %>
      <%= f.collection_select :category_id, Category.all, :id, :name, prompt: true, class: "form-control" %>
    </div>
     <%= f.submit yield(:btn_text), class: "btn btn-primary" %>     
  <% end %>
</div>

app/views/admin/products/_form_new.html.erb
<div class="col-xs-10 col-xs-offset-1 col-sm-10 col-sm-offset-1 col-md-8 col-offset-2 col-lg-8 col-lg-offset-2">
  <%= form_for [:admin, @product] do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <h4><%= t "product" %></h4>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :price %>
      <%= f.number_field :price, step: 0.01, min: 0, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :descriptions %>
      <%= f.text_area :descriptions, size: "10x10", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :category_id %>
      <%= f.collection_select :category_id, Category.all, :id, :name, prompt: true, class: "form-control" %>
    </div>
    <%= link_to_add_fields t("add_type_product"), f ,:type_products %> 
    <div class="new-fields">
      <%= f.fields_for :type_products do |builder| %>
        <%= render "type_product_fields", f: builder %>
      <% end %>
    </div>
     <%= f.submit yield(:btn_text), class: "btn btn-primary" %>     
  <% end %>
</div>

app/views/admin/products/_product.html.erb
<tr>
  <td><%= product.id %></td>
  <td><%= product.name %></td>
  <td><%= product.price %></t>
  <td><%= product.category.name %></td>
  <td><%= product.descriptions %></t>
  <td><%= link_to t("admin.show"), admin_product_path(product) %></td>
  <td><%= link_to t("admin.edit"), edit_admin_product_path(product) %></td>
  <td><%= link_to t("admin.delete"), admin_product_path(id: product.id), method: :delete, data: { confirm: t("admin.products.index.you_sure") } %></td>
</tr>

app/views/admin/products/_type_product_fields.html.erb
<fieldset class="field">
  <h4 class="text-center"><%= t "type_product" %></h4>
  <div class="form-group field">
    <%= f.label :quantity %>
    <%= f.number_field :quantity, step: 1, min: 0, class: "form-control" %>
  </div>
  <div class="form-group field">
    <%= f.label :size %>
    <%= f.number_field :size, min: 30, class: "form-control" %>
  </div>
  <div class="form-group field">
    <%= f.label :color %>
    <%= f.text_field :color, class: "form-control" %>
  </div>
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, t("remove_type_product") %>
</fieldset>

app/views/admin/products/edit.html.erb
<% provide :title, t(:home_title) %>
<% provide :btn_text, t(".submit") %>
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="h2 text-center"><%= t ".title" %></div>
  </div>
  <div class="margin-left-15 margin-top-15">
    <%= link_to t("admin.back"), admin_categories_path, class:"btn btn-success" %>
  </div>
  <div class="panel-body">
    <%= render "form_edit", category: @category %>
  </div>
</div>

app/views/admin/products/index.html.erb
<% provide :title, t(:home_title) %>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-primary">
        <div class="panel-heading">
          <div class="h2 text-center"><%= t ".title" %></div>
        </div>
      </div>
      <div class="panel-body">
        <!-- search box -->
        <div class="row">
          <div class="col-md-8 col-md-offset-2">
            <%= form_tag admin_products_path, method: :get do %>
              <div class="input-group">
                <%= text_field_tag "search", params[:search], placeholder: t(".placeholer"), class: "form-control"%>
                <div class="input-group-btn">
                  <%= button_tag(type: "submit", class: "btn btn-default") do %>
                    <i class="fa fa-search"></i>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <!-- close search box -->
        <!-- button new product -->
        <div class="text-right">
          <%= link_to new_admin_product_path, class: "btn btn-primary" do %>
           <i class="fa fa-plus fa-2x" aria-hidden="true"></i>
          <% end %>
        </div>
        <!-- close button new product -->
        <!-- table product -->
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th><%= t ".id" %></th>
              <th><%= sort_link t(".name") %></th>
              <th><%= sort_link t(".price") %></th>
              <th><%= t ".category" %></th>
              <th class="text-center"><%= t ".descriptions" %></th>
              <th colspan="3" class="text-center"><%= t ".function" %></th>
            </tr>
          </thead>
          <tbody>
            <%= render partial: "product", collection: @products %>
          </tbody>
        </table>
        <!-- close table product -->
        <div class="text-center">
          <%= paginate @products, theme: "twitter-bootstrap-3" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<% provide :title, t(:home_title) %>
<% provide :btn_text, t(".submit") %>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="h2 text-center"><%= t ".title" %></div>
  </div>
  <div class="panel-body">
    <div class="margin-top-15 margin-left-15">
      <%= link_to t("admin.back"), admin_products_path, class:"btn btn-success" %>
    </div>
    <%= render "form_new", product: @product %>
  </div>  
</div>

app/views/admin/products/show.html.erb
<% provide :title, t(:home_title) %>
<% provide :btn_text, t(".submit") %>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="h2 text-center"><%= t ".title" %></div>
  </div>
  <div class="panel-body">
    <div class="margin-top-15 margin-left-15">
      <%= link_to t("admin.back"), admin_products_path, class:"btn btn-success" %>
    </div>
    <%= render "form", product: @product %>
  </div>  
</div>